from __future__ import annotations

# Canonical server-side answers for validating Memorable Set submissions.
MEMORABLE_SCENARIOS = {
    "memorable:ws7-top-9": [
        {
            "id": "memorable-813024-72",
            "pitcher": "Jeff Hoffman",
            "batter": "Enrique Hernández",
            "availableGroups": ["FOUR_SEAM", "SLIDER", "SPLITTER_FORK"],
            "actual": ["SLIDER", "SLIDER", "SLIDER", "SLIDER"],
        },
        {
            "id": "memorable-813024-73",
            "pitcher": "Jeff Hoffman",
            "batter": "Miguel Rojas",
            "availableGroups": ["FOUR_SEAM", "SLIDER", "SPLITTER_FORK"],
            "actual": [
                "SLIDER",
                "SLIDER",
                "FOUR_SEAM",
                "FOUR_SEAM",
                "FOUR_SEAM",
                "SLIDER",
                "SLIDER",
            ],
        },
        {
            "id": "memorable-813024-74",
            "pitcher": "Jeff Hoffman",
            "batter": "Shohei Ohtani",
            "availableGroups": ["FOUR_SEAM", "SLIDER", "SPLITTER_FORK"],
            "actual": ["SPLITTER_FORK"],
        },
        {
            "id": "memorable-813024-75",
            "pitcher": "Jeff Hoffman",
            "batter": "Will Smith",
            "availableGroups": ["FOUR_SEAM", "SLIDER", "SPLITTER_FORK"],
            "actual": ["SLIDER", "SLIDER", "SLIDER", "SLIDER", "SLIDER", "FOUR_SEAM"],
        },
    ],
    "memorable:ws7-bottom-9": [
        {
            "id": "memorable-813024-78",
            "pitcher": "Blake Snell",
            "batter": "Addison Barger",
            "availableGroups": ["FOUR_SEAM", "SLIDER", "CURVE", "CHANGEUP"],
            "actual": [
                "SLIDER",
                "FOUR_SEAM",
                "CURVE",
                "SLIDER",
                "CHANGEUP",
                "CURVE",
                "SLIDER",
                "CURVE",
                "FOUR_SEAM",
            ],
        },
        {
            "id": "memorable-813024-79",
            "pitcher": "Yoshinobu Yamamoto",
            "batter": "Alejandro Kirk",
            "availableGroups": [
                "FOUR_SEAM",
                "MOVING_FASTBALL",
                "CURVE",
                "SPLITTER_FORK",
            ],
            "actual": ["SPLITTER_FORK", "MOVING_FASTBALL"],
        },
        {
            "id": "memorable-813024-80",
            "pitcher": "Yoshinobu Yamamoto",
            "batter": "Daulton Varsho",
            "availableGroups": [
                "FOUR_SEAM",
                "MOVING_FASTBALL",
                "CURVE",
                "SPLITTER_FORK",
            ],
            "actual": ["SPLITTER_FORK", "SPLITTER_FORK", "FOUR_SEAM", "SPLITTER_FORK"],
        },
        {
            "id": "memorable-813024-81",
            "pitcher": "Yoshinobu Yamamoto",
            "batter": "Ernie Clement",
            "availableGroups": [
                "FOUR_SEAM",
                "MOVING_FASTBALL",
                "CURVE",
                "SPLITTER_FORK",
            ],
            "actual": ["CURVE"],
        },
    ],
    "memorable:sf-bottom-9": [
        {
            "id": "memorable-823215-80",
            "pitcher": "Gus Varland",
            "batter": "Matt Chapman",
            "availableGroups": ["FOUR_SEAM", "SLIDER", "CHANGEUP"],
            "actual": ["FOUR_SEAM", "SLIDER", "FOUR_SEAM"],
        },
        {
            "id": "memorable-823215-81",
            "pitcher": "Gus Varland",
            "batter": "Rafael Devers",
            "availableGroups": ["FOUR_SEAM", "SLIDER", "CHANGEUP"],
            "actual": [
                "SLIDER",
                "FOUR_SEAM",
                "FOUR_SEAM",
                "FOUR_SEAM",
                "FOUR_SEAM",
                "FOUR_SEAM",
            ],
        },
        {
            "id": "memorable-823215-82",
            "pitcher": "Mitchell Parker",
            "batter": "Jung Hoo Lee",
            "availableGroups": ["FOUR_SEAM", "SLIDER", "CURVE"],
            "actual": ["SLIDER", "SLIDER", "SLIDER", "CURVE", "FOUR_SEAM"],
        },
        {
            "id": "memorable-823215-83",
            "pitcher": "Mitchell Parker",
            "batter": "Bryce Eldridge",
            "availableGroups": ["FOUR_SEAM", "SLIDER", "CURVE"],
            "actual": ["SLIDER", "SLIDER", "CURVE"],
        },
    ],
    "memorable:bal-bottom-9": [
        {
            "id": "memorable-776443-65",
            "pitcher": "Yoshinobu Yamamoto",
            "batter": "Jackson Holliday",
            "availableGroups": [
                "FOUR_SEAM",
                "MOVING_FASTBALL",
                "SLIDER",
                "CURVE",
                "SPLITTER_FORK",
            ],
            "actual": ["FOUR_SEAM", "SPLITTER_FORK", "FOUR_SEAM", "MOVING_FASTBALL"],
        },
        {
            "id": "memorable-776443-66",
            "pitcher": "Blake Treinen",
            "batter": "Jeremiah Jackson",
            "availableGroups": ["FOUR_SEAM", "MOVING_FASTBALL", "SLIDER"],
            "actual": [
                "MOVING_FASTBALL",
                "SLIDER",
                "SLIDER",
                "SLIDER",
                "MOVING_FASTBALL",
                "SLIDER",
                "MOVING_FASTBALL",
            ],
        },
        {
            "id": "memorable-776443-67",
            "pitcher": "Blake Treinen",
            "batter": "Gunnar Henderson",
            "availableGroups": ["FOUR_SEAM", "MOVING_FASTBALL", "SLIDER"],
            "actual": [
                "SLIDER",
                "MOVING_FASTBALL",
                "MOVING_FASTBALL",
                "FOUR_SEAM",
                "SLIDER",
            ],
        },
        {
            "id": "memorable-776443-68",
            "pitcher": "Blake Treinen",
            "batter": "Ryan Mountcastle",
            "availableGroups": ["FOUR_SEAM", "MOVING_FASTBALL", "SLIDER"],
            "actual": ["SLIDER", "FOUR_SEAM", "SLIDER", "MOVING_FASTBALL", "FOUR_SEAM"],
        },
        {
            "id": "memorable-776443-69",
            "pitcher": "Blake Treinen",
            "batter": "Colton Cowser",
            "availableGroups": ["FOUR_SEAM", "MOVING_FASTBALL", "SLIDER"],
            "actual": [
                "MOVING_FASTBALL",
                "MOVING_FASTBALL",
                "FOUR_SEAM",
                "MOVING_FASTBALL",
                "SLIDER",
            ],
        },
        {
            "id": "memorable-776443-70",
            "pitcher": "Tanner Scott",
            "batter": "Emmanuel Rivera",
            "availableGroups": ["FOUR_SEAM"],
            "actual": ["FOUR_SEAM", "FOUR_SEAM", "FOUR_SEAM"],
        },
    ],
    "memorable:alcs7-bottom-7": [
        {
            "id": "memorable-813037-55",
            "pitcher": "Bryan Woo",
            "batter": "Addison Barger",
            "availableGroups": ["FOUR_SEAM", "MOVING_FASTBALL", "SLIDER"],
            "actual": [
                "MOVING_FASTBALL",
                "FOUR_SEAM",
                "FOUR_SEAM",
                "FOUR_SEAM",
                "FOUR_SEAM",
            ],
        },
        {
            "id": "memorable-813037-56",
            "pitcher": "Bryan Woo",
            "batter": "Isiah Kiner-Falefa",
            "availableGroups": ["FOUR_SEAM", "MOVING_FASTBALL", "SLIDER"],
            "actual": ["FOUR_SEAM", "MOVING_FASTBALL", "SLIDER"],
        },
        {
            "id": "memorable-813037-57",
            "pitcher": "Bryan Woo",
            "batter": "Andrés Giménez",
            "availableGroups": ["FOUR_SEAM", "MOVING_FASTBALL", "SLIDER"],
            "actual": ["FOUR_SEAM", "FOUR_SEAM"],
        },
        {
            "id": "memorable-813037-58",
            "pitcher": "Eduard Bazardo",
            "batter": "George Springer",
            "availableGroups": ["MOVING_FASTBALL", "SLIDER"],
            "actual": ["MOVING_FASTBALL", "MOVING_FASTBALL"],
        },
    ],
}

MEMORABLE_VERSION_LABELS = {
    "memorable:ws7-top-9": "World Series Game 7 · 9회초 · LAD 공격",
    "memorable:ws7-bottom-9": "World Series Game 7 · 9회말 · TOR 공격",
    "memorable:sf-bottom-9": "WSH @ SF · 9회말 · SF 공격",
    "memorable:bal-bottom-9": "LAD @ BAL · 9회말 · 2아웃 이후",
    "memorable:alcs7-bottom-7": "ALCS Game 7 · 7회말 · TOR 공격",
}
